version: '3'

services:

  main:
    image: registry
    ports:
      - "5000:5000"
    volumes:
      - main:/var/lib/registry
    deploy:
      resources:
        reservations:
          memory: 100M

volumes:
  main:
    driver: rexray